### PR TITLE
fix: options no longer ignored in createListener

### LINKED ISSUE #20: createListener: options ignored
It seems the options argument is ignored in createListener. It is overwritten on index.js#L103. Is there a reason for this? If not, I suggest we use the same technique used on index.js#L31 to disable trickle-ice but pass the options along.
I can create a PR if we come to an agreement.

### PR DESCRIPTION
**Pull request by backkem**
The options passed to createListener are now passed through to SimplePeer as done in the dial function.

closes #20

### CODE REVIEW

**Comment by backkem** [comment]
Regarding the test failing: On my machine the tests fail with or without this change. This seems to be due to the time it takes the ICE candidate gathering process to finish. This takes almost 30s on my machine which is far greater than the test timeout. The example in #22 runs fine with this change.

In addition, you can now alter (or remove) the default STUN servers used by SimplePeer by passing the options: ``{config:{}}`` to dial and createListener. This makes the example in #22 complete almost instantly. This obviously loses NAT traversal but that seems fine for testing.

I also tried disabling the STUN servers in the test cases. This makes them all green on my machine. This seems like a good way to make them more reliable. The Server-Reflexive candidates won't be usable anyway since both peers are on the local machine, behind the same NAT. Let me know if this is a change you are comfortable with @vasco-santos and I'll add it to this PR.

**Comment by vasco-santos** [comment]
Hello @backkem 

Thanks for this PR. The tests seem to not be green in Node@10 as a result of an ongoing issue with electron-wrtc.

Taking into consideration disabling the STUN servers in the test cases I am not entirely sure about it. However, if you create a PR later with that single change, we can discuss it further.

**Comment by backkem** [comment]
I created a separate PR (#24) for disabling the STUN servers. It doesn't conflict with this one but won't have an effect until this PR is merged and the options are passed to simple-peer.

Let me know how you want to proceed with this PR. As mentioned in the accompanying ticket:
> Created a PR without a test. I'm honestly not sure how add tests for this change. I may be able to with some pointers but my JavaScript is too limited to come up with one myself.

**Review by vasco-santos — APPROVED** [review]
LGTM!

Since there are currently no other options being used by this module it was working well before.

Note: CI errors are due to an ongoing issue with electron-wrtc.

**Comment by backkem** [comment]
Great, thanks! (Note that I don't have write access to the repo so someone else will have to merge.)

**Pull request merged**
