### PR TITLE
add 'node-pre-gyp' installation to 'check' and 'test-node' actions

### PR DESCRIPTION
**Pull request by vogdb**
cc @vasco-santos

### CODE REVIEW

**Review by wemeetagain — APPROVED** [review]

**Comment by vogdb** [comment]
I can't manage Windows CI to pass. Please advice if you can.

**Comment by vasco-santos** [comment]
> 

It looks like windows installation problem with node-pre-gyp

**Comment by vogdb** [comment]
> It looks like windows installation problem with node-pre-gyp

Yeah. This I understand but I have no clue why it happens. The package author recommends to switch to `@mapbox/node-pre-gyp`. I will try it.

**Comment by vogdb** [comment]
Ok, it's ready. Please squash the PR when merging.

**Review by vasco-santos — APPROVED** [review]
❤️  Thanks

**Comment by vogdb** [comment]
@vasco-santos thank you. I see that CI failed on the merged PR. `AEGIR_GHTOKEN` needs to be set. Please look.
```
8s
Run npm run --if-present release

> libp2p-webrtc-direct@0.7.1 release
> aegir release --target node --target browser

Missing GitHub access token. Have you set `AEGIR_GHTOKEN`?
Error: Process completed with exit code 1.
```

**Comment by vasco-santos** [comment]
@achingbrain can you please setup token? I think we also need NPM token?

**Pull request merged**
