### PR TITLE
replace 'require' dependency with 'native-fetch'

### PR DESCRIPTION
**Pull request by vogdb**
Hi, @vasco-santos! So, I've started as you approved. The only direct dependency, that requires a replacement, is `require`. Other problematic dependencies come from `aegir` and `libp2p-interfaces-compliance-tests`. They should be addressed in their repos correspondingly. One question. I see in the package.json:
```json
"libp2p-interfaces-compliance-tests": "https://gitpkg.now.sh/libp2p/js-libp2p-interfaces/packages/compliance-tests?chore/skip-abort-while-reading-for-webrtc",
```
should it be changed to?
```json
"libp2p-interfaces-compliance-tests": "^4.0.0",
```
or even to?
```json
"@libp2p/interface-compliance-tests": "^1.0.0"
```

### CODE REVIEW

**Comment by vasco-santos** [comment]
Hi @vogdb 
So, we have issue https://github.com/libp2p/js-libp2p-webrtc-direct/issues/117 that has been blocking updating the interfaces module. We need to either fix that bug, or PR interfaces repo doing the same that current linked commit does, in order to get newest interface-compliance-tests dep (but still behind a temporary branch).

On fetch side, I think we should probably use https://www.npmjs.com/package/native-fetch . What do you think?

**Comment by vogdb** [comment]
I will address the interfaces module issue in a separate PR then. I've replaced 'node-fetch' with 'native-fetch'. During tests I've noticed this warning:
```
(node:111179) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:111179) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
```

Should I be considered about it? It certainly comes from using 'native-fetch'.

**Comment by vogdb** [comment]
I see that CI failed. I will look at it tomorrow.

**Comment by vasco-santos** [comment]
> Should I be considered about it?

No worries about it. We use it already in other modules within the stack

**Comment by vogdb** [comment]
That's interesting. In node@v12 'native-fetch' exports `undefined` for its values
```js
const fetch  = require('native-fetch')
console.log(fetch)
```
```
~/.nvm/versions/node/v12.18.3/bin/node ~/workspace/3rdparty/ipfs/js-libp2p-webrtc-direct/deleteme.js
{
  Headers: undefined,
  Request: undefined,
  Response: undefined,
  fetch: undefined
}
```
Should I create an issue in 'native-fetch' repo or remove CI for node@v12 here? I see that 'native-fetch' CI tests only for node@v16. I need your advice here.

**Comment by vasco-santos** [comment]
> Should I create an issue in 'native-fetch' repo or remove CI for node@v12 here?

Good catch. Yes please, Nodev12 is not in maintenance anymore https://nodejs.org/en/about/releases/  . Please also set engines in package json for newer versions of Node like we have in https://github.com/libp2p/js-peer-id/blob/master/package.json#L33

**Comment by vogdb** [comment]
@vasco-santos I would need your advice again. Windows' CI is still using node@v12. Where can I update it? How to change it?\

btw, what about replacing Travis with Github workflow?

**Comment by vasco-santos** [comment]
Github actions yes, this seems the only repo still in travis. You have an example in https://github.com/libp2p/js-libp2p-webrtc-star/blob/master/.github/workflows/js-test-and-release.yml

We can also drop that windows job as this should work in github actions only

**Comment by vogdb** [comment]
Great then, I will replace Travis with Github Actions in a separate PR.

**Comment by vasco-santos** [comment]
> Great then, I will replace Travis with Github Actions in a separate PR.

Sounds good. I will merge this as is

**Review by vasco-santos — APPROVED** [review]
LGTM

**Comment by vogdb** [comment]
Great! I'm waiting for your answers in #150 then.

**Pull request merged**
